apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: noode 
  janus-idp.io/tekton: noode
  backstage.io/kubernetes-id: noode
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: noode
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  